name: CI
 
on:
  push:
    branches: ["main"]
    paths:
      - 'apps/**'
      - 'pkgs/**'
  pull_request:
    types: [opened, synchronize]
 
jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: ğŸ–Šï¸ Log
        uses: ./.github/actions/logger

      - name: ğŸ”§ Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ“¥ Pnpm install
        uses: ./.github/actions/pnpm-install

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test
      
      - name: Publish to surge.sh
        uses: dswistowski/surge-sh-action@v1.0.1
        with:
          domain: 'knit.surge.sh'
          project: './dist/web'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}

