name: CI
 
on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]
 
jobs:
  build:
    name: Build and Test
    permissions:
      contents: write
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: ðŸ–Šï¸ Log
        env:
          LOG_TITLE: '\#\# ðŸ”¨ ci.build started - $(date +%R)\\n'
          COMMITER: 'git log -1 --pretty=format:%ce'
          COMMIT_MSG: 'git log -1 --pretty=format:%s'
          LOG_FILE_PATH: 'logs/$(date +%y%m%d).${{ github.job }}.gen.md'
          LOG_CONTENTS: '$(LOG_TITLE)\> \#\#\# $(COMMIT_MSG)\\n\> by $(COMMITER)\\n\\n'
        run: |
          eval touch $LOG_FILE_PATH
          eval echo -e $LOG_CONTENTS >> $(eval echo $LOG_FILE_PATH)
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "log: write ci build log"
          git push

      - name: ðŸ”§ Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ðŸ“¥ Monorepo install
        uses: ./.github/actions/pnpm-install

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test
